### ISSUE TITLE
No longer working due to Unirest changes

### ISSUE THREAD

**Issue by angelxmoreno** [oauth-io/sdk-php#13]
Due to the fact that the composer file has mashape/unirest-php pointing to dev-master rather than a specific release, and also the fact that the sdk is not compatible with the 2.0 version of unirest; the sdk no longer works. 

I will attempt to fix and send a PR

**Comment by angelxmoreno** [comment]
changes made and tested. PR submitted

**Comment by ahmadnassri** [comment]
this is fixed in #16 as well
